version: "3.1"
services:
  islasgeci:
    build:
      context: .
      dockerfile: Dockerfile
    image: islasgeci/rabbits_on_clarion_island:latest
    command: bash
    volumes:
      - $PWD:/workdir
